<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>

		<ApplicationIcon>iconos\logo.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="iconos\logo.ico" />
		<None Remove="iconos\logo.png" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="iconos\logo.ico">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="iconos\logo.png">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>